[package]
name = "gfx_hal"
version = "0.1.0"
edition = "2021"

[dependencies]
ash.workspace = true
ash-window.workspace = true
thiserror.workspace = true
tracing.workspace = true
winit.workspace = true
