[package]
name = "resource_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
ash.workspace = true
gpu-allocator.workspace = true
thiserror.workspace = true
parking_lot.workspace = true
tracing.workspace = true

gfx_hal = { path = "../gfx_hal" }
