[package]
name = "scene"
version = "0.1.0"
edition = "2021"

[dependencies]
ash.workspace = true
thiserror.workspace = true
tracing.workspace = true
glam.workspace = true
gltf.workspace = true

shared = { path = "../shared" }
resource_manager = { path = "../resource_manager" }
